global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          host: 'bootc'
      - targets: ['nas:9100']
        labels:
          host: 'nas'
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: '/metrics'
    honor_labels: false

  - job_name: 'perses'
    static_configs:
      - targets: ['perses:8080']
    metrics_path: '/metrics'
    scrape_interval: 15s
  - job_name: 'homeassistant'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['homeassistant.story-beta.ts.net:443']
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: '/api/prometheus'
    honor_labels: false

  - job_name: 'unifi-poller'
    static_configs:
      - targets: ['unifi-poller:9130']
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: '/metrics'

  - job_name: 'yfinancer'
    static_configs:
      - targets: ['yfinancer:9101']
    scrape_interval: 60s
    scrape_timeout: 10s
    metrics_path: '/metrics'